# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: remove cfg files
  block:

  - name: check if cfg files are present
    stat:
      path: "{{ httpd_template.dest }}"
    loop: "{{ _httpd_templates.template_options }}"
    loop_control:
      loop_var: httpd_template
      label: "{{ httpd_template.dest }}"
    register: _httpd_cfg_files

  - name: cfg files are replaced
    copy:
      dest: "{{ httpd_template.dest }}"
      content: '# removed file by ansible'
      mode: "{{ httpd_cfg_mode }}"
      backup: true
    loop: "{{ _httpd_templates.template_options }}"
    loop_control:
      loop_var: httpd_template
      label: "{{ httpd_template.dest }}"
      index_var: httpd_i
    when:
    - httpd_template.dest != httpd_main_cfg
    - httpd_conf_d_wr is not defined
    # only if file exists, i.e. don't create it
    - _httpd_cfg_files.results[httpd_i].stat.exists

  - name: cfg files are absent
    file:
      path: "{{ httpd_conf_d }}/{{ httpd_template.dest|basename }}"
      state: absent
    loop: "{{ _httpd_templates.template_options }}"
    loop_control:
      loop_var: httpd_template
      label: "{{ httpd_conf_d }}/{{ httpd_template.dest|basename }}"
    when:
    - httpd_template.dest != httpd_main_cfg
    notify: reload httpd

  when: httpd_templates is defined

...
