# vim: set ft=yaml ts=2 expandtab:
---

- name: converge apache
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  pre_tasks:

  - name: yum repo for scl is present
    package:
      name: centos-release-scl-rh

  roles:

  - role: mafalb.apache.httpd
    scl_prefix: httpd24

  tasks:

  - name: index.html is present
    copy:
      content: "{{ ansible_host }}"
      dest: "/opt/rh/httpd24/root/var/www/html/index.html"
      mode: '644'

...
