# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-apache
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-apache is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-apache is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-apache.
# If not, see <https://www.gnu.org/licenses/>.

---

httpd_packages:
- httpd

httpd_configtest: /usr/sbin/apachectl configtest
httpd_service: httpd
httpd_basedir: /etc/httpd
httpd_basedir: /var/log/httpd
httpd_user: apache

httpd_main_cfg: /etc/httpd/conf/httpd.conf
httpd_conf_d: /etc/httpd/conf.d
httpd_vhosts_d: /etc/httpd/{{ httpd_different_vhosts_d|default('conf.d') }}
httpd_modules_d: /etc/httpd/conf.modules.d

httpd_has_vhosts_d: false
httpd_documentroot: /var/www/html

httpd_default_config:
  ServerRoot: "{{ httpd_basedir }}"
  Listen: 80
  Include: "conf.modules.d/*.conf"
  User: apache
  Group: apache
  ServerAdmin: root@localhost
  DocumentRoot: "{{ httpd_documentroot }}"

  'Directory /':
    _Directory: /
    AllowOverride: none
    Require: all denied

  'Directory document_root_parent':
    _Directory: "{{ httpd_documentroot|dirname }}"
    Allowoverride: none
    Require: all granted

  'Directory documentroot':
    _Directory: "{{ httpd_documentroot }}"
    Options: Indexes FollowSymlinks
    AllowOverride: none
    Require: all granted

  'IfModule dir_module':
    _IfModule: dir_module
    DirectoryIndex: index.html

  'Files .ht*':
    _Files: .ht*
    Require: all denied

  ErrorLog: "logs/error_log"
  LogLevel: warn

  'IfModule log_config_module':
    _IfModule: log_config_module
    Logformat:
    - '"%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined'
    - '"%h %l %u %t \"%r\" %>s %b" common'
    'IfModule logio_module':
      _IfModule: logio_module
      LogFormat: '"%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio'
    CustomLog: '"logs/access_log" combined'

  'IfModule alias_module':
    _IfModule: alias_module
    ScriptAlias: '/cgi-bin/ "{{ httpd_documentroot|dirname }}/cgi-bin"'

  'Directory cgi-bin"':
    _Directory: "{{ httpd_documentroot|dirname }}/cgi-bin"
    AllowOverride: none
    Options: none
    Require: all granted

  'IfModule mime_module':
    _IfModule: mime_module
    TypesConfig: /etc/mime.types
    AddType:
    - application/x-compress .Z
    - application/x-gzip .gz .tgz
    - text/html .shtml
    AddOutputFilter: INCLUDES .shtml

  AddDefaultCharset: UTF-8

  'IfModule mime_magic_module':
    _IfModule: mime_magic_module
    MimeMagicFile: conf/magic

  EnableSendfile: 'on'
  IncludeOptional: conf.d/*.conf

httpd:
  cfg: "{{ httpd_default_config|combine(httpd_config) }}"

...
