# vim: set ft=yaml ts=2 expandtab:
---

httpd_packages:
- httpd

httpd_service: httpd
httpd_basedir: /etc/httpd

httpd_main_cfg: /etc/httpd/conf/httpd.conf
httpd_main_template: httpd.conf-Redhat-7.j2
httpd_conf_d: /etc/httpd/conf.d
httpd_vhosts_d: /etc/httpd/{{ httpd_different_vhosts_d|default('conf.d') }}

httpd_conf_symlink: false
httpd_has_vhosts_d: false

...
