# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-apache
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-apache is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-apache is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-apache.
# If not, see <https://www.gnu.org/licenses/>.

---

httpd_packages:
- "{{ httpd_scl_prefix }}-httpd"

httpd_configtest: 'scl enable {{ httpd_scl_prefix }} "apachectl configtest"'
httpd_service: "{{ httpd_scl_prefix }}-httpd"

httpd_documentroot: /opt/{{ httpd_scl_provider }}/{{ httpd_scl_name }}/root/var/www/html
httpd_basedir: /opt/{{ httpd_scl_provider }}/{{ httpd_scl_name }}/root/etc/httpd
httpd_logdir: /var/log/{{ httpd_scl_prefix }}
httpd_main_cfg: /opt/{{ httpd_scl_provider }}/{{ httpd_scl_name }}/root/etc/httpd/conf/httpd.conf

httpd_conf_d: /opt/{{ httpd_scl_provider }}/{{ httpd_scl_name }}/root/etc/httpd/conf.d
httpd_vhosts_d: /opt/{{ httpd_scl_provider }}/{{ httpd_scl_name }}/root/etc/httpd/{{ httpd_different_vhosts_d|default('conf.d') }}
httpd_modules_d: /opt/{{ httpd_scl_provider }}/{{ httpd_scl_name }}/root/etc/httpd/conf.modules.d

httpd_scl_provider: "{{ httpd_scl_prefix|mafalb.scl.provider }}"
httpd_scl_name: "{{ httpd_scl_prefix|mafalb.scl.name }}"

...
