# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: converge apache
  hosts: ci_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: mafalb.apache.httpd
  - role: mafalb.apache.httpd
    tasks: cfg
    httpd_templates:
    - dest: /root/my_httpd_config.conf
      yaml:
        LogFormat: '"%h gugu" justforCI'

...
