# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-apache
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-apache is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-apache is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-apache.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: include mafalb.apache.httpd with scl
  include_role:
    name: mafalb.apache.httpd
  vars:
    httpd_scl_prefix: httpd24
    httpd_templates:
    - src: test.conf.j2
      dest: test.conf
  when: scl is defined

- name: include mafalb.apache.httpd without scl
  include_role:
    name: mafalb.apache.httpd
  vars:
    httpd_templates:
    - src: test.conf.j2
      dest: test.conf
  when: not scl is defined

...
