# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: OS specific stuff
  block:

  - name: check that OS is supported
    assert:
      that:
      - ansible_os_family in ['Rocky','RedHat','Debian']

  - name: include OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"


- name: SCL specific stuff
  block:

  - name: assert that OS is supported
    assert:
      that:
      - ansible_os_family == 'RedHat'
      - ansible_os_family != 'Fedora'
      - ansible_distribution_major_version == '7'

  - name: include SCL specific variables
    include_vars: scl.yml

  - name: debug
    debug: var=httpd_scl_provider
  - name: debug
    debug: var=httpd_scl_name
    tags:
    - never
    - debug

  when: httpd_scl_prefix is defined

- name: assert that state is valid
  assert:
    that: state|default('present') in ['present', 'absent', 'vars']

- name: include tasks
  include_tasks: "{{ state|default('present') }}.yml"
  when: state|default('present') in ['present','absent']

...
