# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-apache
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-apache is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-apache is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-apache.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: OS specific stuff
  block:

  - name: check that OS is supported
    assert:
      that:
      - ansible_os_family in ['Rocky','RedHat','Debian']

  - name: include OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"


- name: SCL specific stuff
  block:

  - name: assert that OS is supported
    assert:
      that:
      - ansible_os_family == 'RedHat'
      - ansible_os_family != 'Fedora'
      - ansible_distribution_major_version == '7'

  - name: include SCL specific variables
    include_vars: scl.yml

  - name: debug
    debug: var=scl_provider
  - name: debug
    debug: var=scl_name
    tags:
    - never
    - debug

  when: scl_prefix is defined

- name: assert that state is valid
  assert:
    that: state in ['present', 'absent', 'vars']

- name: include_tasks for {{ sshd_state }}
  include_tasks: "{{ state }}.yml"
  when: state in ['present','absent']

...
