# vim: set ft=yaml ts=2 expandtab:
---

- name: OS specific stuff
  block:

  - name: check that OS is supported
    assert:
      that:
      - ansible_os_family in ['RedHat','Debian']

  - name: include OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
    - "{{ ansible_os_family }}.yml"


- name: SCL specific stuff
  block:

  - name: assert that OS is supported
    assert:
      that:
      - ansible_os_family == 'RedHat'
      - ansible_os_family != 'Fedora'
      - ansible_distribution_major_version == '7'

  - name: include SCL specific variables
    include_vars: scl.yml

  - debug: var=scl_provider
  - debug: var=scl_name
    tags:
    - never
    - debug

  when: scl_prefix is defined


- name: apache is present
  package:
    name: "{{ httpd_packages }}"

- debug: var=httpd_vhosts_d

- name: additional directories are present
  file:
    path: "{{ httpd_vhosts_d }}"
    state: directory
    mode: '755'

- name: apache is configured
  template:
    src: "{{ item.src }}"
    dest: "{{ httpd_conf_d }}/{{ item.dest }}"
    mode: "{{ httpd_cfg_mode }}"
    backup: true
  loop: "{{ httpd_templates }}"
  when: httpd_templates is defined
  notify: reload httpd
  register: _httpd_templates

- name: symlink if necessary (e.g. on debian)
  file:
    src: "{{ httpd_conf_d }}/{{ item.dest }}"
    dest: "{{ httpd_basedir }}/conf-enabled/{{ item.dest }}"
    state: link
  loop: "{{ httpd_templates }}"
  when:
  - httpd_templates is defined
  - httpd_conf_symlink|bool
  register: _httpd_symlinks

- block:
  - debug: var=_httpd_templates
  - debug: var=_httpd_symlinks
  tags:
  - never
  - debug

- name: apache is started
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: "{{ httpd_service_enabled }}"
  register: _httpd_has_started

...
