# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: apache config is present  # noqa risky-file-permissions
  template: "{{ httpd_template }}"
  vars:
    httpd_cfg_dict: >
      {{ httpd_default_config|combine(httpd_templates[i].yaml|default({}))
      if httpd_template.dest == httpd_main_cfg
      else httpd_templates[i].yaml|default({}) }}
  loop: "{{ _httpd_templates.template_options }}"
  loop_control:
    loop_var: httpd_template
    index_var: i
  notify: reload httpd
  #register: _httpd_templates

- name: symlink if necessary (e.g. on debian)
  file:
    src: "{{ httpd_conf_d_wr }}/{{ httpd_template.dest }}"
    dest: "{{ httpd_conf_d }}/{{ httpd_template.dest }}"
    state: link
  loop: "{{ _httpd_templates.template_options }}"
  loop_control:
    loop_var: httpd_template
  when:
  - httpd_conf_d_wr is defined
  - httpd_template.dest != httpd_main_cfg
  notify: reload httpd
  register: _httpd_symlinks

- name: check config
  command: "{{ httpd_configtest }}"
  register: _configtest
  changed_when: false

- block:
  - name: debug
    debug: var=_httpd_templates
  - name: debug
    debug: var=_httpd_symlinks
  - name: debug
    debug: var=_configtest
  tags:
  - never
  - debug

...
